global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  # etc...

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:9091']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'processor'
    static_configs:
      - targets: ['processor:9092']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']